version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

homebrew_casks:
  - name: emu-sync
    binaries:
      - emu-sync
    homepage: "https://github.com/jacobfgrant/emu-sync"
    description: "Sync ROMs and BIOS files from an S3-compatible bucket"
    repository:
      owner: jacobfgrant
      name: homebrew-tap
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emu-sync"]

nfpms:
  - package_name: emu-sync
    maintainer: "Jacob F. Grant git@jacobfgrant.com"
    homepage: "https://github.com/jacobfgrant/emu-sync"
    description: "Sync ROMs and BIOS files from an S3-compatible bucket"
    formats:
      - deb
